repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        exclude: /test
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--config', 'api/.flake8']
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
    -   id: validate-html
        args: [--remove-mustaches, --mustache-remover=jinja2, "--ignore=Duplicate ID \"DUMMY\""]
        exclude: "component/*"
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
    -   id: scss-lint
