# name: Deploy python pacakage to PyPi

# on:
#   release:
#     types: [released]

# jobs:
#   release:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Populate .env with additional vars
#         run: |
#           echo "AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }}" >> .env
#           echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
#           echo "TWINE_USERNAME=${{ secrets.TWINE_USERNAME }}" >> .env
#           echo "TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }}" >> .env
#           echo TWINE_NON_INTERACTIVE=${{ secrets.TWINE_NON_INTERACTIVE }} >> .env

#       - name: Install Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install python reqs
#         run: |
#           python3 -m pip install twine

#       - name: Release
#         run: |
#           make deploy/pypi
